import { Activity, BarChart3, Download, FilterX, LockKeyhole, PieChart, Search, ShieldCheck } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useEffect, useMemo, useState } from "react";
import { ScreenHeader } from "@/components/ScreenHeader";
import { auditEntries } from "@/lib/demo";
import { getAuditAnalytics, getAuditFilters, getAuditLog, type AuditAnalytics, type AuditEvent, type AuditFilterState, type AuditFilters } from "@/lib/auditApi";

const defaultFilters: AuditFilterState = { range: "30", action: "all", actor: "all", entityType: "all", outcome: "all" };
const fallbackAnalytics: AuditAnalytics = { period_days: 30, timeline: [{ date: "2026-08-22", scored: 12, drafts: 4, reviews: 2, imports: 0 }, { date: "2026-08-23", scored: 18, drafts: 3, reviews: 1, imports: 0 }, { date: "2026-08-24", scored: 15, drafts: 6, reviews: 3, imports: 1 }, { date: "2026-08-25", scored: 24, drafts: 4, reviews: 2, imports: 0 }, { date: "2026-08-26", scored: 21, drafts: 5, reviews: 3, imports: 2 }, { date: "2026-08-27", scored: 30, drafts: 7, reviews: 4, imports: 1 }], chargeback_trends: [{ date: "2026-08-22", opened: 3, awaiting_review: 1, reviewed: 2 }, { date: "2026-08-23", opened: 5, awaiting_review: 2, reviewed: 3 }, { date: "2026-08-24", opened: 4, awaiting_review: 2, reviewed: 2 }, { date: "2026-08-25", opened: 6, awaiting_review: 3, reviewed: 3 }, { date: "2026-08-26", opened: 4, awaiting_review: 1, reviewed: 3 }, { date: "2026-08-27", opened: 7, awaiting_review: 3, reviewed: 4 }] };
const fallbackEvents: AuditEvent[] = auditEntries.map((entry, index) => ({ event_id: `demo-${index}`, action: entry.action, entity_type: entry.entity.startsWith("dsp") ? "dispute" : "transaction", entity_id: entry.entity, actor: entry.actor, model_version: entry.model, input_hash: "demo-audit", output: { message: entry.result }, occurred_at: entry.time.replace(" ", "T").replace(" UTC", "+00:00") }));
const formatAction = (value: string) => value.replaceAll("_", " ");
const displayDate = (value: string) => new Intl.DateTimeFormat("en-IN", { month: "short", day: "numeric" }).format(new Date(value));

export default function AuditLog() {
  const [filters, setFilters] = useState(defaultFilters); const [query, setQuery] = useState(""); const [events, setEvents] = useState<AuditEvent[]>(fallbackEvents); const [analytics, setAnalytics] = useState<AuditAnalytics>(fallbackAnalytics); const [options, setOptions] = useState<AuditFilters>({ actions: [], actors: [], entity_types: [] }); const [live, setLive] = useState(false);
  useEffect(() => { let active = true; Promise.all([getAuditFilters(), getAuditLog(filters), getAuditAnalytics(filters.range)]).then(([nextOptions, nextEvents, nextAnalytics]) => { if (!active) return; setOptions(nextOptions); setEvents(nextEvents); setAnalytics(nextAnalytics); setLive(true); }).catch(() => active && setLive(false)); return () => { active = false; }; }, [filters]);
  const visible = useMemo(() => events.filter(event => Object.values({ ...event, output: JSON.stringify(event.output) }).join(" ").toLowerCase().includes(query.toLowerCase())), [events, query]);
  const totals = useMemo(() => ({ scored: analytics.timeline.reduce((total, day) => total + day.scored, 0), drafts: analytics.timeline.reduce((total, day) => total + day.drafts, 0), reviews: analytics.timeline.reduce((total, day) => total + day.reviews, 0), imports: analytics.timeline.reduce((total, day) => total + day.imports, 0) }), [analytics]);
  const change = <K extends keyof AuditFilterState>(key: K, value: AuditFilterState[K]) => setFilters(current => ({ ...current, [key]: value }));
  const exportCsv = () => { const headers = ["utc_timestamp", "action", "entity_type", "entity_id", "actor", "model_version", "input_hash", "output"]; const rows = visible.map(event => [event.occurred_at, event.action, event.entity_type, event.entity_id, event.actor, event.model_version ?? "", event.input_hash, JSON.stringify(event.output)].map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")); const link = document.createElement("a"); const url = URL.createObjectURL(new Blob([[headers.join(","), ...rows].join("\n")], { type: "text/csv" })); link.href = url; link.download = "chargebackshield-audit-export.csv"; link.click(); URL.revokeObjectURL(url); };
  return <div className="screen-shell audit-enhanced"><ScreenHeader eyebrow="Governance / filter, inspect, explain" title="Audit intelligence"><button className="outline-button" onClick={exportCsv}><Download size={16} />Export filtered log</button></ScreenHeader>
    <section className="audit-summary"><LockKeyhole size={18} /><p><strong>Append-only, inspectable, and filterable.</strong> Every score, draft, import, and human review is stored with a model version, input hash, actor, output summary, and UTC timestamp. {live ? "Live reference-service data is displayed." : "Demo data is displayed while the reference service is unavailable."}</p></section>
    <section className="analytics-strip"><article className="analytics-title"><p className="eyebrow">Audit activity / {filters.range} days</p><h2>What changed, and why.</h2><span><ShieldCheck size={15} />{live ? "Live audit stream" : "Safe demo stream"}</span></article><article><Activity size={17} /><b>{totals.scored}</b><small>Transactions scored</small></article><article><BarChart3 size={17} /><b>{totals.drafts}</b><small>Evidence drafts</small></article><article><PieChart size={17} /><b>{totals.reviews}</b><small>Human reviews</small></article><article><Download size={17} /><b>{totals.imports}</b><small>CSV import events</small></article></section>
    <div className="audit-charts"><section className="sketch-card audit-chart-card"><div className="card-heading"><div><p className="eyebrow">Event velocity</p><h2>Risk review activity</h2></div><span className="chart-caption">Scores · drafts · decisions</span></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={analytics.timeline}><defs><linearGradient id="scoreAudit" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#3395FF" stopOpacity=".6" /><stop offset="100%" stopColor="#3395FF" stopOpacity=".04" /></linearGradient></defs><CartesianGrid vertical={false} stroke="#D9D0C2" strokeDasharray="3 5" /><XAxis dataKey="date" tickFormatter={displayDate} tickLine={false} axisLine={false} fontSize={11} /><YAxis tickLine={false} axisLine={false} fontSize={11} /><Tooltip labelFormatter={displayDate} contentStyle={{ borderRadius: 14, border: "1px dashed #2F2B29", background: "#FFFCF4" }} /><Legend iconSize={8} /><Area isAnimationActive={false} type="monotone" dataKey="scored" name="Scored" stackId="1" stroke="#3395FF" fill="url(#scoreAudit)" /><Area isAnimationActive={false} type="monotone" dataKey="drafts" name="Drafts" stackId="1" stroke="#E3A33A" fill="#F6D586" /><Area isAnimationActive={false} type="monotone" dataKey="reviews" name="Reviews" stackId="1" stroke="#45A77A" fill="#9BDEC1" /></AreaChart></ResponsiveContainer></div></section>
      <section className="sketch-card audit-chart-card"><div className="card-heading"><div><p className="eyebrow">Chargeback queue</p><h2>Opened vs. resolved</h2></div><span className="chart-caption">Dispute state, UTC day</span></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.chargeback_trends} barGap={3}><CartesianGrid vertical={false} stroke="#D9D0C2" strokeDasharray="3 5" /><XAxis dataKey="date" tickFormatter={displayDate} tickLine={false} axisLine={false} fontSize={11} /><YAxis tickLine={false} axisLine={false} fontSize={11} /><Tooltip labelFormatter={displayDate} contentStyle={{ borderRadius: 14, border: "1px dashed #2F2B29", background: "#FFFCF4" }} /><Legend iconSize={8} /><Bar isAnimationActive={false} dataKey="opened" name="Opened" fill="#3395FF" radius={[5, 5, 0, 0]} /><Bar isAnimationActive={false} dataKey="awaiting_review" name="Awaiting review" fill="#F0A646" radius={[5, 5, 0, 0]} /><Bar isAnimationActive={false} dataKey="reviewed" name="Reviewed" fill="#42A978" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></section></div>
    <section className="filter-console sketch-card"><div className="filter-console-top"><div><p className="eyebrow">Audit query builder</p><h2>Find a decision in context</h2></div><button onClick={() => { setFilters(defaultFilters); setQuery(""); }} className="reset-filter"><FilterX size={15} />Reset filters</button></div><div className="advanced-filters"><label>Period<select value={filters.range} onChange={event => change("range", event.target.value as AuditFilterState["range"])}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></label><label>Action<select value={filters.action} onChange={event => change("action", event.target.value)}><option value="all">All actions</option>{options.actions.map(value => <option key={value}>{formatAction(value)}</option>)}</select></label><label>Actor<select value={filters.actor} onChange={event => change("actor", event.target.value)}><option value="all">All actors</option>{options.actors.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>Entity<select value={filters.entityType} onChange={event => change("entityType", event.target.value)}><option value="all">All entities</option>{options.entity_types.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>Outcome type<select value={filters.outcome} onChange={event => change("outcome", event.target.value as AuditFilterState["outcome"])}><option value="all">All outcomes</option><option value="model">Model scoring</option><option value="review">Human review</option><option value="import">CSV intake</option></select></label></div></section>
    <div className="audit-tools"><label className="search-field"><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search action, actor, ID, hash, or output" /></label><span>{visible.length} matching append-only events</span></div><section className="sketch-card audit-table-card"><table className="audit-table"><thead><tr><th>UTC timestamp</th><th>Action</th><th>Entity</th><th>Actor</th><th>Model version</th><th>Recorded output</th></tr></thead><tbody>{visible.map(event => <tr key={event.event_id}><td className="mono">{new Date(event.occurred_at).toLocaleString("en-GB", { timeZone: "UTC" })} UTC</td><td><span className="audit-action">{formatAction(event.action)}</span></td><td><span className="mono">{event.entity_type}</span><small className="entity-id">{event.entity_id}</small></td><td>{event.actor}</td><td className="mono model-cell">{event.model_version ?? "—"}<small>{event.input_hash.slice(0, 10)}…</small></td><td>{String(event.output.message ?? event.output.status ?? event.output.rows ?? "Recorded")}</td></tr>)}</tbody></table>{visible.length === 0 && <div className="audit-empty"><Search size={22} /><strong>No matching audit events</strong><span>Try a wider date range or reset a filter.</span></div>}</section>
  </div>;
}
