import { Check, ClipboardCheck, Download, FileWarning, Loader2, ShieldAlert, X } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { ScreenHeader, formatInr } from "@/components/ScreenHeader";
import { disputes, evidenceDraft } from "@/lib/demo";
import { approveEvidence, downloadEvidencePdf, generateEvidence, rejectEvidence } from "@/lib/riskApi";
import type { EvidenceDraft } from "@shared/types";

export default function EvidenceGenerator() {
  const [location] = useLocation(); const query = new URLSearchParams(location.split("?")[1]); const [selected, setSelected] = useState(query.get("dispute") || "dsp_demo_001");
  const [draft, setDraft] = useState<EvidenceDraft>(evidenceDraft); const [state, setState] = useState<"idle" | "loading" | "approved" | "rejected">("idle"); const [notice, setNotice] = useState(""); const [rejectionReason, setRejectionReason] = useState("Reviewer rejected the draft for further evidence collection.");
  const dispute = disputes.find(item => item.disputeId === selected) ?? disputes[1];
  const generate = async () => { setState("loading"); setNotice(""); try { const live = await generateEvidence(dispute.disputeId); setDraft(live); setNotice("Live source-linked draft generated from the local FastAPI evidence service."); } catch (error) { setNotice(error instanceof Error ? error.message : "Evidence generation failed."); } finally { setState("idle"); } };
  const approve = async () => { try { setNotice(await approveEvidence(dispute.disputeId)); setState("approved"); } catch (error) { setNotice(error instanceof Error ? error.message : "Approval failed."); } };
  const reject = async () => { try { await rejectEvidence(dispute.disputeId, rejectionReason); setState("rejected"); setNotice("Rejection reason recorded in the audit trail."); } catch (error) { setNotice(error instanceof Error ? error.message : "Rejection failed."); } };
  const exportPdf = async () => { try { await downloadEvidencePdf(dispute.disputeId); setNotice("PDF export prepared from the source-linked draft; the export action was recorded in the audit trail."); } catch (error) { setNotice(error instanceof Error ? error.message : "PDF export failed."); } };
  return <div className="screen-shell evidence-screen"><ScreenHeader eyebrow="Evidence studio / bounded & reviewable" title="Build a defensible response"><div className="header-evidence-actions"><button className="outline-button" onClick={exportPdf}><Download size={16} />Export PDF</button><button className="solid-button" onClick={generate} disabled={state === "loading"}>{state === "loading" ? <Loader2 className="animate-spin" size={16} /> : <ClipboardCheck size={16} />}Generate evidence</button></div></ScreenHeader>
    <section className="evidence-layout"><aside className="evidence-selector sketch-card"><p className="eyebrow">Open dispute</p>{disputes.map(item => <button className={selected === item.disputeId ? "dispute-select active" : "dispute-select"} onClick={() => { setSelected(item.disputeId); setState("idle"); setNotice(""); }} key={item.disputeId}><span>{item.reason}</span><small>{item.customer} · {formatInr(item.amount)}</small></button>)}<div className="dashed-rule" /><div className="review-context"><p>Current review</p><strong>{dispute.reason}</strong><span>{dispute.dueText}</span></div></aside>
      <main className="draft-paper sketch-card"><div className="draft-meta"><span className="eyebrow">Draft {draft.draftId}</span><span className={draft.hasSufficientEvidence ? "evidence-state sufficient" : "evidence-state insufficient"}>{draft.hasSufficientEvidence ? "Grounded evidence available" : "Evidence gaps disclosed"}</span></div><h2>Evidence response draft</h2><p className="draft-lead">Every statement below is linked to retrieved structure. The system does not add merchant claims beyond the supplied source records.</p><div className="claim-list">{draft.claims.map(claim => <article className={`claim-block ${claim.type}`} key={claim.claimId}><p>{claim.claim}</p><div className="source-links">{claim.sourceLinks.length ? claim.sourceLinks.map((source, index) => <span key={`${source.sourceRecordId}-${index}`}><b>{source.sourceEntity.replace("_", " ")}</b> · {source.sourceField}: {source.sourceValue}</span>) : <span className="no-source">No source supports this claim.</span>}</div></article>)}</div>{draft.insufficientEvidence.length > 0 && <div className="insufficient-note"><FileWarning size={18} /><div><strong>Evidence gaps requiring attention</strong>{draft.insufficientEvidence.map(item => <span key={item}>{item}</span>)}</div></div>}<div className="reviewer-panel"><label htmlFor="rejection-reason">Reviewer note if declining this draft</label><textarea id="rejection-reason" value={rejectionReason} onChange={event => setRejectionReason(event.target.value)} maxLength={1000} placeholder="State what evidence must be collected before continuing." /></div><div className="draft-actions"><button className="approve-button" onClick={approve} disabled={state === "loading" || state === "approved"}><Check size={17} />{state === "approved" ? "Approval recorded" : "Approve local submission"}</button><button className="reject-button" onClick={reject} disabled={state === "loading" || state === "rejected" || rejectionReason.trim().length < 3}><X size={17} />{state === "rejected" ? "Rejected" : "Reject with reason"}</button></div>{notice && <p className="action-notice">{notice}</p>}</main>
      <aside className="audit-panel sketch-card"><div className="audit-title"><ShieldAlert size={18} /><div><p className="eyebrow">Audit trail</p><h3>How this was built</h3></div></div><ol><li><span>01</span><p><strong>Retrieved</strong><small>Transaction, order, delivery, communications, device history.</small></p></li><li><span>02</span><p><strong>Constrained</strong><small>Only source-key-linked JSON claims are accepted.</small></p></li><li><span>03</span><p><strong>Awaiting reviewer</strong><small>Draft is not submitted externally.</small></p></li></ol><div className="hash-box"><span>Input hash</span><code>7fac99…de0f1</code><small>UTC {new Date(draft.createdAt).toLocaleString()}</small></div></aside>
    </section></div>;
}
