import { ChevronDown, Filter, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { ScreenHeader, RiskBadge, formatInr } from "@/components/ScreenHeader";
import { transactions } from "@/lib/demo";

export default function RiskFeed() {
  const [filter, setFilter] = useState<"all" | "low" | "medium" | "high">("all");
  const [expanded, setExpanded] = useState<string | null>("txn_demo_001");
  const filtered = useMemo(() => transactions.filter(item => filter === "all" || item.tier === filter), [filter]);
  return <div className="screen-shell"><ScreenHeader eyebrow="Risk intelligence / review before action" title="Transaction risk feed"><button className="outline-button"><SlidersHorizontal size={16} />Tune policy</button></ScreenHeader>
    <section className="filter-strip sketch-card"><div className="filter-copy"><Filter size={16} /><strong>Filters</strong><span>Showing 4 scored transactions from the synthetic demo stream.</span></div><div className="filter-controls"><label>Risk tier<select value={filter} onChange={event => setFilter(event.target.value as typeof filter)}><option value="all">All tiers</option><option value="high">High risk</option><option value="medium">Medium risk</option><option value="low">Low risk</option></select></label><label>Method<select defaultValue="all"><option value="all">All methods</option><option>Card</option><option>UPI</option><option>Wallet</option></select></label></div></section>
    <section className="sketch-card feed-card"><div className="feed-grid feed-head"><span>Transaction</span><span>Context</span><span>Amount</span><span>Score & tier</span><span>Recommended action</span><span /></div>{filtered.map(item => <div className="feed-row-wrap" key={item.transactionId}><button className="feed-grid feed-row" onClick={() => setExpanded(expanded === item.transactionId ? null : item.transactionId)} aria-expanded={expanded === item.transactionId}><span className="mono">{item.transactionId}<small>{item.occurredAt}</small></span><span>{item.customer}<small>{item.method}</small></span><span className="amount">{formatInr(item.amount)}</span><span><RiskBadge tier={item.tier} /><strong>{Math.round(item.riskScore * 100)}%</strong></span><span><b className={`action action-${item.tier}`}>{item.action}</b></span><ChevronDown className={expanded === item.transactionId ? "chevron-open" : ""} size={18} /></button>{expanded === item.transactionId && <div className="explain-panel"><div><p className="eyebrow">SHAP-style feature contribution</p><h3>Why this score moved</h3><p className="body-copy">The model presents its strongest feature effects for review. This is an explanation, not an automated decision.</p></div><div className="contribution-list">{item.factors.map(factor => <div className="contribution" key={factor.feature}><div className="contribution-label"><span>{factor.displayName}</span><small>{factor.evidence}</small></div><div className="contribution-track"><i className={factor.direction === "raises_risk" ? "raise" : "lower"} style={{ width: `${Math.min(Math.abs(factor.contribution) * 70 + 12, 100)}%` }} /></div><strong className={factor.direction === "raises_risk" ? "raise-text" : "lower-text"}>{factor.contribution > 0 ? "+" : ""}{factor.contribution.toFixed(2)}</strong></div>)}</div></div>}</div>)}</section>
  </div>;
}
